version: '3.8'

services:
  # Base de datos SQL
  postgres:
    image: postgres:15-alpine
    container_name: kahoot_postgres
    restart: always
    environment:
      # Lee estas variables del archivo .env de la raíz
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de datos en RAM (Cache y Pub/Sub)
  redis:
    image: redis:alpine
    container_name: kahoot_redis
    restart: always
    ports:
      # El puerto también es configurable por seguridad
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes

  # Panel visual para depurar Redis (Opcional)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: kahoot_redis_ui
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  postgres_data: